### ISSUE TITLE
crash of blender when saving images

### ISSUE THREAD

**Issue by itada** [sobotka/AgX#13]
Hi Troy.
I have freshly installed the AgX (replaced the colour management files), set up the colour management in blender and did a test render on a relatively complex project. The render preview works ok and it renders smoothly but when I want to save the PNGs blender crashes.

I am on Windows 10 64 bit, portable blender 3.4.1, i7 and RTX2070
The whole system info generated from blender attached below.
[system-info.txt](https://github.com/sobotka/AgX/files/11168009/system-info.txt)

**Comment by sobotka** [comment]
Nothing to do with the configuration if Blender crashes.

Software should never crash. Try with the most recent version of Blender and report a crash report over on Blender proper.

**Comment by itada** [comment]
I have tested with 3.5 Blender. The render results can be saved with standard colour management but when I install the AgX it crashes immediately after clicking the save button. 
The problem is only when AgX is installed.

**Comment by sobotka** [comment]
Please trust me when I repeat what I said:

**No software should ever crash**.

A segmentation fault or any such thing will *always* be on the software to fail gracefully. No debates are permitted here as *any and all segmentation or other faults are the basis of critical security flaws*.

I suspect you have colour transforms in the saved file that are not present in this demonstration configuration.

However, the point stands: This is not the configuration. This is faulty code in Blender that is causing the crash.
